<script lang="ts">
  import type { WorkspaceDocument } from "@app/database/database";
  import { WorkspaceRole } from "@sparrow/common/enums";
  import GrpcExplorerViewModel from "./GrpcExplorerPage.ViewModel";
  import { onDestroy } from "svelte";
  import { GrpcExplorer } from "@sparrow/workspaces/features";
  import { getClientUser } from "@app/utils/jwt";
  import { user } from "@app/store/auth.store";

  export let tab;

  let userId = "";
  let userRole = "";
  let _viewModel;
  let environments;
  let activeWorkspace;
  let isGrpcEditable = false;
  let currentWorkspace;
  let currentWorkspaceId = "";
  let environmentId = "";
  let activeWorkspaceSubscribe;

  user.subscribe((value) => {
    if (value) {
      userId = value._id;
    }
  });

  const findUserRole = async () => {
    const workspace = await _viewModel.getWorkspaceById(
      tab?.path?.workspaceId as string,
    );
    workspace.users?.forEach((value) => {
      if (value.id === userId) {
        userRole = value.role as string;
      }
    });
  };

  let prevTabId = "";
  $: {
    if (tab) {
      if (prevTabId !== tab?.tabId) {
        (async () => {
          _viewModel = new GrpcExplorerViewModel(tab);
          environments = _viewModel.environments;
          activeWorkspace = _viewModel.activeWorkspace;

          activeWorkspaceSubscribe = activeWorkspace.subscribe(
            async (value: WorkspaceDocument) => {
              const activeWorkspaceRxDoc = value.toMutableJSON();
              if (activeWorkspaceRxDoc) {
                currentWorkspace = activeWorkspaceRxDoc;
                currentWorkspaceId = activeWorkspaceRxDoc._id;
                environmentId = activeWorkspaceRxDoc.environmentId as string;
                const clientUserId = getClientUser().id;
                if (clientUserId) {
                  let isUserViewer = false;
                  activeWorkspaceRxDoc.users?.forEach((_user) => {
                    if (_user.id === clientUserId) {
                      if (_user.role === WorkspaceRole.WORKSPACE_VIEWER) {
                        isUserViewer = true;
                      }
                    }
                  });
                  if (isUserViewer) {
                    isGrpcEditable = false;
                  } else {
                    isGrpcEditable = true;
                  }
                }
              }
            },
          );
          await findUserRole();
        })();
        prevTabId = tab?.tabId;
      }
    }
  }

  onDestroy(() => {
    if (activeWorkspaceSubscribe) {
      activeWorkspaceSubscribe.unsubscribe();
    }
  });
</script>

{#if _viewModel}
  <GrpcExplorer
    tab={_viewModel.tab}
    collections={_viewModel.collections}
    requestAuthHeader={_viewModel.authHeader}
    onUpdateRequestUrl={_viewModel.onUpdateRequestUrl}
    onUpdateRequestAuth={_viewModel.onUpdateRequestAuth}
    onUpdateHeaders={_viewModel.onUpdateHeaders}
    onUpdateAutoGeneratedHeaders={_viewModel.onUpdateAutoGeneratedHeaders}
    onUpdateRequestState={_viewModel.onUpdateRequestState}
    onUpdateServices={_viewModel.onUpdateServices}
    onSaveRequest={_viewModel.handleSaveGrpc}
    environmentVariables={_viewModel.environmentVariables}
    onUpdateEnvironment={_viewModel.onUpdateEnvironment}
    {isGrpcEditable}
    {userRole}
  />
{/if}
