export enum GrpcRequestAuthTypeTabEnum {
  NO_AUTH = "No Auth",
  API_KEY = "API Key",
  BEARER_TOKEN = "Bearer Token",
  BASIC_AUTH = "Basic Auth",
}

export enum GrpcRequestSectionTabEnum {
  SERVICE = "Service",
  MESSAGE = "Message",
  AUTHORIZATION = "Authorization",
  METADATA = "Metadata",
}

export interface GrpcRequestKeyWrapperTabInterface {
  key: string;
}
export interface GrpcRequestValueWrapperTabInterface {
  value: string;
}
export interface GrpcRequestCheckedWrapperTabInterface {
  checked: boolean;
}

export interface GrpcRequestLeftSplitterWidthPercentageWrapperTabInterface {
  requestLeftSplitterWidthPercentage: number;
}
export interface GrpcRequestRightSplitterWidthPercentageWrapperTabInterface {
  requestRightSplitterWidthPercentage: number;
}

export interface GrpcRequestIsBulkMetadataWrapperTabInterface {
  isMetadataBulkEditActive: boolean;
}

export interface GrpcRequestProtoLoadedWrapperTabInterface {
  isProtoLoaded: boolean;
}

export interface GrpcRequestUsernameWrapperTabInterface {
  username: string;
}
export interface GrpcRequestPasswordWrapperTabInterface {
  password: string;
}
export interface GrpcRequestAuthKeyWrapperTabInterface {
  authKey: string;
}
export interface GrpcRequestAuthValueWrapperTabInterface {
  authValue: string;
}

export interface GrpcRequestBearerTokenWrapperTabInterface {
  bearerToken: string;
}
export interface GrpcRequestUrlWrapperTabInterface {
  url: string;
}
export interface GrpcRequestProtoPathWrapperTabInterface {
  protoPath: string;
}
export interface GrpcRequestSelectedServiceWrapperTabInterface {
  selectedService: string;
}
export interface GrpcRequestSelectedMethodWrapperTabInterface {
  selectedMethod: string;
}
export interface GrpcRequestMessageWrapperTabInterface {
  message: string;
}

export interface GrpcRequestKeyValueCheckedTabInterface
  extends GrpcRequestKeyWrapperTabInterface,
    GrpcRequestValueWrapperTabInterface,
    GrpcRequestCheckedWrapperTabInterface {}

export interface GrpcRequestNavigationWrapperTabInterface {
  requestNavigation: GrpcRequestSectionTabEnum;
}
export interface GrpcRequestAuthNavigationWrapperTabInterface {
  requestAuthNavigation: GrpcRequestAuthTypeTabEnum;
}
export interface GrpcRequestStateTabInterface
  extends GrpcRequestNavigationWrapperTabInterface,
    GrpcRequestAuthNavigationWrapperTabInterface,
    GrpcRequestLeftSplitterWidthPercentageWrapperTabInterface,
    GrpcRequestRightSplitterWidthPercentageWrapperTabInterface,
    GrpcRequestIsBulkMetadataWrapperTabInterface,
    GrpcRequestProtoLoadedWrapperTabInterface {}

export interface GrpcRequestStateWrapperTabInterface {
  state: GrpcRequestStateTabInterface;
}

export interface GrpcRequestBasicAuthTabInterface
  extends GrpcRequestUsernameWrapperTabInterface,
    GrpcRequestPasswordWrapperTabInterface {}
export interface GrpcRequestBasicAuthWrapperTabInterface {
  basicAuth: GrpcRequestBasicAuthTabInterface;
}
export interface GrpcRequestApiKeyTabInterface
  extends GrpcRequestAuthKeyWrapperTabInterface,
    GrpcRequestAuthValueWrapperTabInterface {}
export interface GrpcRequestApiKeyWrapperTabInterface {
  apiKey: GrpcRequestApiKeyTabInterface;
}
export interface GrpcRequestAuthTabInterface
  extends GrpcRequestBearerTokenWrapperTabInterface,
    GrpcRequestBasicAuthWrapperTabInterface,
    GrpcRequestApiKeyWrapperTabInterface {}
export interface GrpcRequestAuthWrapperTabInterface {
  auth: GrpcRequestAuthTabInterface;
}

export interface GrpcRequestMetadataWrapperTabInterface {
  metadata: GrpcRequestKeyValueCheckedTabInterface[];
}

export interface GrpcRequestAutoGeneratedMetadataWrapperTabInterface {
  autoGeneratedMetadata: GrpcRequestKeyValueCheckedTabInterface[];
}

export interface GrpcRequestWrapperTabInterface {
  grpc: GrpcRequestTabInterface;
}

export interface GrpcRequestTabInterface
  extends GrpcRequestAutoGeneratedMetadataWrapperTabInterface,
    GrpcRequestStateWrapperTabInterface,
    GrpcRequestAuthWrapperTabInterface,
    GrpcRequestUrlWrapperTabInterface,
    GrpcRequestProtoPathWrapperTabInterface,
    GrpcRequestSelectedServiceWrapperTabInterface,
    GrpcRequestSelectedMethodWrapperTabInterface,
    GrpcRequestMessageWrapperTabInterface,
    GrpcRequestMetadataWrapperTabInterface {}
