<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import { open } from "@tauri-apps/plugin-dialog";
  import { Button, Loader } from "@sparrow/library/ui";
  import { Select } from "@sparrow/library/forms";
  import { notifications } from "@sparrow/library/ui";
  import type { Observable } from "rxjs";
  import type { KeyValue } from "@sparrow/common/types/workspace";

  // Reusing GraphQL components
  import { RequestHeaders } from "../../graphql-explorer/components";
  import { RequestAuth } from "../../graphql-explorer/components";

  export let tab;
  export let collections;
  export let requestAuthHeader: Observable<KeyValue>;
  export let onUpdateRequestUrl;
  export let onUpdateRequestAuth;
  export let onUpdateHeaders;
  export let onUpdateAutoGeneratedHeaders;
  export let onUpdateRequestState;
  export let onUpdateServices;
  export let onSaveRequest;
  export let environmentVariables;
  export let onUpdateEnvironment;
  export let isGrpcEditable = true;
  export let userRole;

  let isLoading = false;
  let services: any[] = [];
  let methods: any[] = [];
  let selectedService = "";
  let selectedMethod = "";
  let protoLoaded = false;
  let requestMessage = "{}";
  let responseData = "";
  let isRequestInProgress = false;
  let activeRequestTab: "message" | "metadata" | "auth" = "message";
  let isTestingConnection = false;
  let isValidJson = true;
  let jsonError = "";

  // Debug: Track method dropdown state
  $: methodDropdownDisabled = !selectedService || methods.length === 0;
  $: {
    console.log("🔍 Method dropdown state:", {
      selectedService,
      methodsCount: methods.length,
      disabled: methodDropdownDisabled,
    });
  }

  // Track if component just initialized (for syncing from saved state)
  let hasInitialized = false;
  let currentTabId = "";

  // Initialize gRPC properties safely - ONLY sync from tab on first load
  $: if ($tab?.property?.grpc) {
    // Check if this is a different tab (tab switch) or just a state update
    const isTabSwitch = currentTabId !== "" && currentTabId !== $tab.tabId;
    const isInitialLoad = !hasInitialized;
    
    // Only sync message from tab state on initial load or when switching to a different tab
    if (isInitialLoad || isTabSwitch) {
      requestMessage = $tab.property.grpc.message || "{}";
      currentTabId = $tab.tabId || "";
      
      const tabSelectedService = $tab.property.grpc.selectedService || "";
      const tabSelectedMethod = $tab.property.grpc.selectedMethod || "";

      if (tabSelectedService) selectedService = tabSelectedService;
      if (tabSelectedMethod) selectedMethod = tabSelectedMethod;
      
      // Mark as initialized on first load
      if (isInitialLoad) {
        hasInitialized = true;
      }
    }

    // Initialize services and methods from tab state (only when reloading from saved state)
    if (($tab.property.grpc as any).services && ($tab.property.grpc as any).services.length > 0) {
      // Only update if we don't have services loaded yet (prevents overwriting after manual load)
      if (services.length === 0) {
        const tabServices = ($tab.property.grpc as any).services;
        services = tabServices;
        protoLoaded = true;

        // Update methods if service is selected
        if (selectedService) {
          const service = services.find((s) => s.full_name === selectedService);
          if (service) {
            methods = service.methods || [];
          }
        }
      }
    }
  }

  function handleRequestTabChange(tab: "message" | "metadata" | "auth") {
    activeRequestTab = tab;
  }

  // Wrapper function for headers update
  function handleHeadersUpdate(headers: any[]) {
    onUpdateHeaders(headers);
  }

  async function handleTestConnection() {
    if (!$tab?.property?.grpc?.url) {
      notifications.error("Please enter a gRPC server URL first");
      return;
    }

    try {
      isTestingConnection = true;
      
      const result = await invoke("test_grpc_connection", {
        url: $tab.property.grpc.url,
      });

      const response = JSON.parse(result as string);
      
      if (response.status === "SUCCESS") {
        notifications.success(
          `✓ Connected to gRPC server (${response.duration_ms}ms)`
        );
      } else {
        notifications.error(`Connection failed: ${response.message}`);
      }
    } catch (error) {
      notifications.error(`Connection test failed: ${error}`);
      console.error(error);
    } finally {
      isTestingConnection = false;
    }
  }

  async function handleLoadProto() {
    try {
      const selected = await open({
        multiple: false,
        filters: [
          {
            name: "Proto Files",
            extensions: ["proto"],
          },
        ],
      });

      if (selected) {
        isLoading = true;
        const result = await invoke("load_grpc_proto", {
          protoPath: selected,
        });

        const parsed = JSON.parse(result as string);
        const loadedServices = parsed.services || [];

        if (loadedServices.length > 0) {
          // Update local state immediately for UI reactivity
          services = loadedServices;
          protoLoaded = true;
          notifications.success("Proto file loaded successfully");

          // Save services to tab state in background
          onUpdateServices(loadedServices);

          // Update tab state
          onUpdateRequestState({
            protoPath: selected,
            isProtoLoaded: true,
          });
        } else {
          notifications.error("No services found in proto file");
        }
      }
    } catch (error) {
      notifications.error(`Failed to load proto: ${error}`);
      console.error(error);
    } finally {
      isLoading = false;
    }
  }

  function handleServiceChange(event: CustomEvent | string) {
    console.log("🎯 handleServiceChange called with:", event);

    let value: string;
    if (typeof event === "string") {
      value = event;
    } else {
      value = event.detail;
    }

    console.log("Selected service value:", value);

    const service = services.find((s) => s.full_name === value);
    console.log("Found service:", service);

    // Update local state - force Svelte reactivity by creating new arrays
    methods = service?.methods ? [...service.methods] : [];
    selectedService = value;
    selectedMethod = "";

    console.log("Methods extracted:", {
      count: methods.length,
      methods: methods,
      selectedService: selectedService,
      selectedMethod: selectedMethod,
    });

    // Save to tab state (background persistence)
    onUpdateRequestState({
      selectedService: value,
      selectedMethod: "",
    });
  }

  function handleMethodChange(event: CustomEvent | string) {
    let value: string;
    if (typeof event === "string") {
      value = event;
    } else {
      value = event.detail;
    }

    selectedMethod = value;

    // Save to tab state (background persistence)
    onUpdateRequestState({
      selectedMethod: value,
    });
  }

  async function handleSendRequest() {
    if (!protoLoaded) {
      notifications.error(
        "Please load a .proto file first using the 'Load Proto File' button",
      );
      return;
    }

    if (!selectedService || !selectedMethod) {
      notifications.error(
        "Please select a service and method from the dropdowns",
      );
      return;
    }

    if (!$tab?.property?.grpc?.url) {
      notifications.error(
        "Please enter gRPC server URL (e.g., http://localhost:50051)",
      );
      return;
    }

    try {
      isRequestInProgress = true;

      // Build metadata from headers
      const metadata: Record<string, string> = {};
      const grpcMetadata = $tab?.property?.grpc?.metadata || [];
      grpcMetadata.forEach((m: any) => {
        if (m.checked && m.key) {
          metadata[m.key] = m.value;
        }
      });

      const result = await invoke("send_grpc_request", {
        url: $tab.property.grpc.url,
        serviceName: selectedService,
        methodName: selectedMethod,
        metadata: JSON.stringify(metadata),
        message: requestMessage,
      });

      responseData = result as string;
      
      // Parse response to show appropriate notification
      try {
        const parsedResponse = JSON.parse(result as string);
        if (parsedResponse.status === "OK") {
          notifications.success(`✓ gRPC request completed (${parsedResponse.duration_ms}ms)`);
        } else {
          notifications.error(`gRPC request failed: ${parsedResponse.message}`);
        }
      } catch {
        notifications.success("gRPC request sent successfully");
      }
    } catch (error) {
      responseData = JSON.stringify({
        status: "ERROR",
        status_code: -1,
        message: `Request failed: ${error}`,
        duration_ms: 0
      });
      notifications.error(`Request failed: ${error}`);
      console.error(error);
    } finally {
      isRequestInProgress = false;
    }
  }

  function handleMessageChange(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    requestMessage = target.value;
    
    // Validate JSON
    try {
      if (requestMessage.trim()) {
        JSON.parse(requestMessage);
        isValidJson = true;
        jsonError = "";
      } else {
        isValidJson = true;
        jsonError = "";
      }
    } catch (error) {
      isValidJson = false;
      jsonError = error instanceof Error ? error.message : "Invalid JSON";
    }
    
    onUpdateRequestState({
      message: requestMessage,
    });
  }
</script>

<div class="grpc-explorer-layout h-100 d-flex flex-column">
  <div class="p-3">
    <!-- URL Input Section -->
    <div class="d-flex gap-2 mb-3">
      <input
        type="text"
        class="form-control url-input"
        placeholder="grpc://localhost:50051 or http://localhost:50051"
        value={$tab?.property?.grpc?.url || ""}
        on:input={(e) => {
          // @ts-ignore
          const target = e.target;
          if (target && target.value !== undefined) {
            onUpdateRequestUrl(target.value);
          }
        }}
      />
      <Button
        title="Test Connection"
        type="secondary"
        loader={isTestingConnection}
        disable={isTestingConnection || !$tab?.property?.grpc?.url}
        onClick={handleTestConnection}
        startIcon=""
        endIcon=""
      />
      <Button
        title={isRequestInProgress ? "Sending..." : "Send"}
        type="primary"
        loader={isRequestInProgress}
        disable={isRequestInProgress || !protoLoaded || !selectedService || !selectedMethod || !isValidJson}
        onClick={handleSendRequest}
        startIcon=""
        endIcon=""
      />
    </div>

    <!-- Helper Text -->
    <div class="mb-3">
      <small class="text-muted">
        Enter your gRPC server URL, load a .proto file, select service and method, then send your request.
        {#if !protoLoaded}
          <strong>Next: Load a proto file</strong>
        {:else if !selectedService}
          <strong>Next: Select a service</strong>
        {:else if !selectedMethod}
          <strong>Next: Select a method</strong>
        {:else}
          <strong>Ready to send!</strong>
        {/if}
      </small>
    </div>

    <!-- Proto File Loader -->
    <div class="mb-3">
      <Button
        title={protoLoaded ? "Change Proto File" : "Load Proto File"}
        type="secondary"
        loader={isLoading}
        onClick={handleLoadProto}
        startIcon=""
        endIcon=""
      />
      {#if protoLoaded}
        <span class="ms-2 text-success">✓ Proto loaded</span>
      {/if}
    </div>

    <!-- Service and Method Selectors -->
    {#if protoLoaded && services.length > 0}
      <div class="row mb-3">
        <div class="col-6">
          <label class="form-label" for="service-select">Service</label>
          <Select
            id="service-select"
            data={services.map((s) => ({ id: s.full_name, name: s.full_name }))}
            titleId={selectedService}
            onclick={handleServiceChange}
            searchText="Search service..."
            menuItem="v2"
            variant="secondary"
            placeholderText="Select a service"
          />
        </div>
        <div class="col-6">
          <label class="form-label" for="method-select">Method</label>
          <Select
            id="method-select"
            data={methods.map((m) => ({ id: m.name, name: m.name }))}
            titleId={selectedMethod}
            onclick={handleMethodChange}
            searchText="Search method..."
            menuItem="v2"
            variant="secondary"
            disabled={methodDropdownDisabled}
            placeholderText={methodDropdownDisabled ? "Select a service first" : "Select a method"}
          />
        </div>
      </div>
    {/if}
  </div>

  <!-- Request/Response Panels -->
  <div class="flex-1 d-flex" style="overflow: hidden;">
    <!-- Request Panel (Left) -->
    <div class="w-50 border-end p-3" style="overflow-y: auto;">
      <h6 class="mb-3">Request</h6>

      <!-- Tabs for Message, Metadata, Auth -->
      <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
          <button
            class="nav-link {activeRequestTab === 'message' ? 'active' : ''}"
            on:click={() => handleRequestTabChange("message")}
          >
            Message
          </button>
        </li>
        <li class="nav-item">
          <button
            class="nav-link {activeRequestTab === 'metadata' ? 'active' : ''}"
            on:click={() => handleRequestTabChange("metadata")}
          >
            Metadata
          </button>
        </li>
        <li class="nav-item">
          <button
            class="nav-link {activeRequestTab === 'auth' ? 'active' : ''}"
            on:click={() => handleRequestTabChange("auth")}
          >
            Auth
          </button>
        </li>
      </ul>

      <!-- Message Editor -->
      {#if activeRequestTab === "message"}
        <div>
          <label class="form-label" for="message-editor"
            >Request Message (JSON)</label
          >
          <textarea
            id="message-editor"
            class="form-control message-editor"
            class:invalid-json={!isValidJson}
            rows="15"
            placeholder={'{\n  "field": "value"\n}'}
            value={requestMessage}
            on:input={handleMessageChange}
          ></textarea>
          {#if !isValidJson && jsonError}
            <div class="json-error mt-1">
              <small class="text-danger">❌ {jsonError}</small>
            </div>
          {:else if isValidJson && requestMessage.trim()}
            <div class="json-valid mt-1">
              <small class="text-success">✓ Valid JSON</small>
            </div>
          {/if}
        </div>
      {:else if activeRequestTab === "metadata"}
        <div>
          <RequestHeaders
            headers={Array.isArray($tab.property.grpc.metadata) ? $tab.property.grpc.metadata : []}
            onHeadersChange={handleHeadersUpdate}
            {environmentVariables}
            onAutoGeneratedHeadersChange={() => {}}
            autoGeneratedHeaders={Array.isArray($tab.property.grpc.autoGeneratedMetadata) ? $tab.property.grpc.autoGeneratedMetadata : []}
            authHeader={$requestAuthHeader}
            {onUpdateEnvironment}
            isBulkEditActive={false}
            {onUpdateRequestState}
          />
        </div>
      {:else if activeRequestTab === "auth"}
        <div>
          <RequestAuth
            auth={$tab.property.grpc.auth || {}}
            requestStateAuth={$tab.property.grpc.state || {}}
            {onUpdateRequestAuth}
            {onUpdateRequestState}
            {environmentVariables}
            {onUpdateEnvironment}
          />
        </div>
      {/if}
    </div>

    <!-- Response Panel (Right) -->
    <div class="w-50 p-3" style="overflow-y: auto;">
      <h6 class="mb-3">Response</h6>
      {#if isRequestInProgress}
        <div class="text-center mt-5">
          <Loader loaderSize="24px" />
          <p class="mt-2">Sending gRPC request...</p>
        </div>
      {:else if responseData}
        <div class="response-container">
          <!-- Response Info Bar -->
          {#if typeof responseData === 'string'}
            {@const parsedResponse = JSON.parse(responseData)}
            <div class="response-info mb-2 p-2 rounded" 
                 class:success={parsedResponse.status === 'OK'}
                 class:error={parsedResponse.status === 'ERROR'}>
              <div class="d-flex justify-content-between align-items-center">
                <span class="status-text">
                  {parsedResponse.status === 'OK' ? '✓' : '✗'} 
                  {parsedResponse.status}
                  {#if parsedResponse.status_code !== undefined}
                    (Code: {parsedResponse.status_code})
                  {/if}
                </span>
                {#if parsedResponse.duration_ms}
                  <span class="duration-text">{parsedResponse.duration_ms}ms</span>
                {/if}
              </div>
            </div>
            
            <!-- Response Body -->
            <pre class="response-viewer">{typeof parsedResponse.message === 'string' ? 
              parsedResponse.message : 
              JSON.stringify(parsedResponse.message, null, 2)}</pre>
          {:else}
            <pre class="response-viewer">{responseData}</pre>
          {/if}
        </div>
      {:else}
        <div class="text-center text-muted mt-5">
          <p>Response will appear here</p>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .grpc-explorer-layout {
    background-color: var(--bg-ds-surface-900);
    color: var(--text-ds-neutral-50);
  }

  .url-input {
    background-color: var(--bg-ds-surface-800);
    border: 1px solid var(--border-ds-neutral-600);
    color: var(--text-ds-neutral-50);
    padding: 8px 12px;
    border-radius: 4px;
  }

  .url-input:focus {
    outline: none;
    border-color: var(--border-ds-primary-300);
  }

  .form-label {
    color: var(--text-ds-neutral-200);
    font-size: 12px;
    font-weight: 500;
    margin-bottom: 4px;
  }

  .message-editor {
    background-color: var(--bg-ds-surface-800);
    border: 1px solid var(--border-ds-neutral-600);
    color: var(--text-ds-neutral-50);
    font-family: "Monaco", "Menlo", monospace;
    font-size: 13px;
    padding: 12px;
    border-radius: 4px;
    resize: vertical;
  }

  .message-editor:focus {
    outline: none;
    border-color: var(--border-ds-primary-300);
  }

  .response-viewer {
    background-color: var(--bg-ds-surface-800);
    border: 1px solid var(--border-ds-neutral-600);
    color: var(--text-ds-neutral-50);
    font-family: "Monaco", "Menlo", monospace;
    font-size: 13px;
    padding: 12px;
    border-radius: 4px;
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
  }

  .nav-tabs {
    border-bottom: 1px solid var(--border-ds-neutral-600);
  }

  .nav-item {
    margin-bottom: -1px;
  }

  .nav-link {
    background: transparent;
    border: none;
    color: var(--text-ds-neutral-300);
    padding: 8px 16px;
    cursor: pointer;
    border-bottom: 2px solid transparent;
    transition: all 0.2s;
  }

  .nav-link:hover {
    color: var(--text-ds-neutral-50);
  }

  .nav-link.active {
    color: var(--text-ds-primary-300);
    border-bottom-color: var(--border-ds-primary-300);
  }

  .text-success {
    color: var(--text-ds-success-300);
    font-size: 13px;
  }

  .border-end {
    border-right: 1px solid var(--border-ds-neutral-700) !important;
  }

  .response-info {
    font-size: 12px;
    border: 1px solid var(--border-ds-neutral-600);
  }

  .response-info.success {
    background-color: var(--bg-ds-success-900);
    border-color: var(--border-ds-success-600);
    color: var(--text-ds-success-100);
  }

  .response-info.error {
    background-color: var(--bg-ds-danger-900);
    border-color: var(--border-ds-danger-600);
    color: var(--text-ds-danger-100);
  }

  .status-text {
    font-weight: 600;
  }

  .duration-text {
    font-family: "Monaco", "Menlo", monospace;
    opacity: 0.8;
  }

  .response-container {
    height: calc(100% - 40px);
    display: flex;
    flex-direction: column;
  }

  .response-viewer {
    flex: 1;
    overflow-y: auto;
  }  .response-info {
    background-color: var(--bg-ds-surface-700);
    border: 1px solid var(--border-ds-neutral-600);
    font-size: 12px;
  }

  .response-info.success {
    background-color: var(--bg-ds-success-800);
    border-color: var(--border-ds-success-600);
    color: var(--text-ds-success-100);
  }

  .response-info.error {
    background-color: var(--bg-ds-danger-800);
    border-color: var(--border-ds-danger-600);
    color: var(--text-ds-danger-100);
  }

  .status-text {
    font-weight: 500;
  }

  .duration-text {
    font-family: "Monaco", "Menlo", monospace;
    opacity: 0.8;
  }

  .response-container {
    height: calc(100% - 40px);
    display: flex;
    flex-direction: column;
  }

  .response-viewer {
    flex: 1;
    overflow-y: auto;
  }

  .invalid-json {
    border-color: var(--border-ds-danger-500) !important;
    box-shadow: 0 0 0 1px var(--border-ds-danger-500);
  }

  .json-error {
    font-size: 11px;
  }

  .json-valid {
    font-size: 11px;
  }

  .text-danger {
    color: var(--text-ds-danger-300);
  }
</style>

