import {
  TabTypeEnum,
  type Tab,
  type Path,
  TabPersistenceTypeEnum,
} from "@sparrow/common/types/workspace/tab";
import { v4 as uuidv4 } from "uuid";
import {
  GrpcRequestAuthTypeTabEnum,
  GrpcRequestSectionTabEnum,
  type GrpcRequestAuthTabInterface,
  type GrpcRequestAutoGeneratedMetadataTabInterface,
  type GrpcRequestMetadataWrapperTabInterface,
  type GrpcRequestStateTabInterface,
} from "../types/workspace/grpc-request-tab";
import { GrpcRequestDefaultAliasBaseEnum } from "../types/workspace/grpc-request-base";

class InitGrpcTab {
  private _tab: Tab;
  /**
   *
   * @param _id - Request mongo id
   * @param _workspaceId - Workspace Id to which Request belongs to
   */
  constructor(_id: string, _workspaceId: string) {
    this._tab = {
      id: _id,
      tabId: uuidv4(),
      name: "New " + GrpcRequestDefaultAliasBaseEnum.NAME,
      type: TabTypeEnum.GRPC,
      persistence: TabPersistenceTypeEnum.PERMANENT,
      description: "",
      source: "USER",
      isDeleted: false,
      activeSync: false,
      property: {
        grpc: {
          url: "",
          protoPath: "",
          selectedService: "",
          selectedMethod: "",
          message: "{}",
          metadata: [
            {
              key: "",
              value: "",
              checked: false,
            },
          ],
          autoGeneratedMetadata: [
            {
              key: "user-agent",
              value: "grpc-sparrow/1.0.0",
              checked: true,
            },
          ],
          state: {
            requestNavigation: GrpcRequestSectionTabEnum.SERVICE,
            requestAuthNavigation: GrpcRequestAuthTypeTabEnum.NO_AUTH,
            requestLeftSplitterWidthPercentage: 50,
            requestRightSplitterWidthPercentage: 50,
            isMetadataBulkEditActive: false,
            isProtoLoaded: false,
          },
          auth: {
            bearerToken: "",
            basicAuth: {
              username: "",
              password: "",
            },
            apiKey: {
              authKey: "",
              authValue: "",
            },
          },
        },
      },
      path: {
        workspaceId: _workspaceId,
        collectionId: "",
        folderId: "",
      },
      isSaved: true,
      index: 0,
      isActive: true,
      timestamp: new Date().toString(),
    };
    if (!_id || !_workspaceId) {
      console.error(
        "invalid id or workspace id on create new grpc tab request!",
      );
    }
  }
  public getValue(): Tab {
    return this._tab;
  }
  public updateUrl(_url: string) {
    this._tab.property.grpc.url = _url;
  }
  public updateProtoPath(_protoPath: string) {
    this._tab.property.grpc.protoPath = _protoPath;
  }
  public updateSelectedService(_service: string) {
    this._tab.property.grpc.selectedService = _service;
  }
  public updateSelectedMethod(_method: string) {
    this._tab.property.grpc.selectedMethod = _method;
  }
  public updateMessage(_message: string) {
    this._tab.property.grpc.message = _message;
  }
  public updateServices(_services: any[]) {
    this._tab.property.grpc.services = _services;
  }
  public updateMetadata(_metadata: any) {
    this._tab.property.grpc.metadata = _metadata;
  }
  public updateAutoGeneratedMetadata(_autoGeneratedMetadata: any) {
    this._tab.property.grpc.autoGeneratedMetadata = _autoGeneratedMetadata;
  }
  public updateAuth(_auth: GrpcRequestAuthTabInterface) {
    this._tab.property.grpc.auth = _auth;
  }
  public updateState(_state: GrpcRequestStateTabInterface) {
    this._tab.property.grpc.state = {
      ..._state,
    };
  }
  public updatePath(_path: Path) {
    this._tab.path = _path;
  }
  public updateIsSave(_isSaved: boolean) {
    this._tab.isSaved = _isSaved;
  }
  public updateName(_name: string) {
    this._tab.name = _name;
  }
  public updateDescription(_description: string) {
    this._tab.description = _description;
  }
  public updateId(_id: string) {
    this._tab.id = _id;
  }
  public updateSource(_source: string) {
    this._tab.source = _source;
  }
  public updateIsDeleted(_isDeleted: boolean) {
    this._tab.isDeleted = _isDeleted;
  }
}

export { InitGrpcTab };
