name: Create JIRA Issue on GitHub Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label is 'bug' or 'feature'
        id: check_label
        run: |
          labels=$(echo "${{ toJson(github.event.issue.labels) }}" | jq -r '.[].name')
          echo "Labels: $labels"
          type="skip"
          for label in $labels; do
            if [[ "$label" == "bug" ]]; then
              type="Bug"
            elif [[ "$label" == "feature" ]]; then
              type="Story"
            fi
          done
          echo "jira_type=$type" >> $GITHUB_OUTPUT

      - name: Exit if label is not bug or feature
        if: steps.check_label.outputs.jira_type == 'skip'
        run: echo "No relevant label found. Skipping JIRA creation."

      - name: Create JIRA issue
        if: steps.check_label.outputs.jira_type != 'skip'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_AUTH_HEADER: ${{ secrets.JIRA_AUTH_HEADER }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          JIRA_ISSUE_TYPE: ${{ steps.check_label.outputs.jira_type }}
        run: |
          curl -X POST \
            -H "Authorization: $JIRA_AUTH_HEADER" \
            -H "Content-Type: application/json" \
            --data '{
              "fields": {
                "project": {
                  "key": "'"$JIRA_PROJECT_KEY"'"
                },
                "summary": "'"${ISSUE_TITLE//\"/\\\"}"'",
                "description": "'"${ISSUE_BODY//\"/\\\"}"'",
                "issuetype": {
                  "name": "'"$JIRA_ISSUE_TYPE"'"
                }
              }
            }' \
            $JIRA_BASE_URL/rest/api/2/issue/
